[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
solc_version = "0.8.26"
evm_version = "cancun"

# Enable via-IR
via-ir = true

# Enable optimizer
optimizer = true

# How many runs for the optimizer
optimizer_runs = 200
